[2024-01-31T11:00:21.440+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_analysis_dag.process_stock_data manual__2024-01-31T11:00:10.124783+00:00 [queued]>
[2024-01-31T11:00:21.444+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_analysis_dag.process_stock_data manual__2024-01-31T11:00:10.124783+00:00 [queued]>
[2024-01-31T11:00:21.444+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-31T11:00:21.454+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): process_stock_data> on 2024-01-31 11:00:10.124783+00:00
[2024-01-31T11:00:21.457+0000] {standard_task_runner.py:60} INFO - Started process 2408 to run task
[2024-01-31T11:00:21.458+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'stock_analysis_dag', 'process_stock_data', 'manual__2024-01-31T11:00:10.124783+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/stock_analysis_dag.py', '--cfg-path', '/tmp/tmp7u4ocm4r']
[2024-01-31T11:00:21.459+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask process_stock_data
[2024-01-31T11:00:21.479+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_analysis_dag.process_stock_data manual__2024-01-31T11:00:10.124783+00:00 [running]> on host de-airflow-vm-instance-1.europe-west10-a.c.dataengineeringfinal-411911.internal
[2024-01-31T11:00:21.516+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='onatpostac@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_analysis_dag' AIRFLOW_CTX_TASK_ID='process_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T11:00:10.124783+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T11:00:10.124783+00:00'
[2024-01-31T11:05:03.417+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-01-31T11:05:03.419+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 2408. PIDs of all processes in the group: [2408]
[2024-01-31T11:05:03.419+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 2408
[2024-01-31T11:05:03.420+0000] {taskinstance.py:2451} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-01-31T11:05:03.447+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2408, status='terminated', exitcode=0, started='11:00:20') (2408) terminated with exit code 0
